# Generated by Django 5.0.3 on 2024-06-14 19:36

import django_resized.forms
import myauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to=myauth.models.product_preview_directory_path,
                verbose_name="Аватар пользователя",
            ),
        ),
    ]
