# Generated by Django 5.0.3 on 2024-06-13 23:58

import django.db.models.deletion
import django_resized.forms
import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_product_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="предпросмотр",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=shopapp.models.product_images_directory_path,
                        verbose_name="Изображение",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shopapp.product",
                    ),
                ),
            ],
        ),
    ]
