# Generated by Django 5.0.3 on 2024-06-14 09:56

import django_resized.forms
import shopapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_alter_product_preview_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to=shopapp.models.product_preview_directory_path,
                verbose_name="Предпросмотр",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to=shopapp.models.product_images_directory_path,
                verbose_name="Изображение",
            ),
        ),
    ]
