# Generated by Django 5.0.3 on 2024-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_product_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=30, verbose_name="Название"
            ),
        ),
    ]
